### ISSUE TITLE
Create a js node for detecting the arucos and placing the bounding box in the correct coordinates

### ISSUE THREAD

**Issue by miguelriemoliveira** [bernardomig/atlas-augmented-perception#12]
Used this js node for arucos
https://github.com/jcmellado/js-aruco

**Comment by bernardomig** [comment]
The code should be put in `atlas-perception-visualization`

**Comment by jbga** [comment]
Code already pushed to `atlas-perception-visualization` : 2f24cda90ee459aa32fa86bcf3c76f7f6beee618

**Comment by miguelriemoliveira** [comment]
If it is working you may close the issue.
