### ISSUE TITLE
Discuss proto messages format

### ISSUE THREAD

**Issue by miguelriemoliveira** [bernardomig/atlas-augmented-perception#6]
@bernardomig create a fisrt draft of the proto messages (definitions for the information that is exchenaged between the hmd device and the computed).

@bernardomig please put here your first suggestion then we iterate.

**Comment by bernardomig** [comment]
The messages were created in the folder interface/protos.
The explanation of the messages are in the README.md in the interface subdirectory.

**Comment by miguelriemoliveira** [comment]
Hi @bernardomig 

Looks great. All I am missing are the instructions for compiling the protos both to python and csharp. I would say the best way is to do a Makefile.

**Comment by bernardomig** [comment]
I just now added it. It's in the README at the bottom.

Just need to explain how to build the client and the server.

**Comment by miguelriemoliveira** [comment]
Hi @bernardomig ,

reviewed the proto messages definitions. Looks good but I have some comments:

**1. Timestamp and Frame_id**

```proto
syntax = "proto3";

package atlas.augmented;

import "BoundingBox3.proto";

message DetectedObject {
    // The unique id of the detected object
    uint64 id = 1;
    // The classification label
    string label = 2;
    // The tridimensional bounding box related to the object
    BoundingBox3 bbox = 3;
}
```

needs a **timestamp** to know when the classification was made, and a **frame_id** to know the reference system in which the bbox position is defined. This is what we normally have in the [ros std_msgs/header](http://docs.ros.org/hydro/api/std_msgs/html/msg/Header.html)

**2. Axis aligned Bboxes only?**

Another question: the way you define the bounding box we can only have axis aligned bboxes. Perhaps fully 3d rotated bboxes would be better? See [this](http://docs.ros.org/hydro/api/std_msgs/html/msg/Header.html)

**3. Tips for defining google protocol buffer messages**

Whenever I am defining the proto messages I always feel like I am reinventing the wheel. One thing I did in the past was to try to align as much as possible with the ROS standard.  Check this

https://github.com/miguelriemoliveira/RustBot/tree/master/rustbot_translation/msgs

For example, I defined a ROS-like header message which was then included into the pointcloud messages and others ...

**Comment by bernardomig** [comment]
ok :+1: . I'll adapt it.

**Comment by miguelriemoliveira** [comment]
If you want you can just copy paste the basic protos from the repo above. I did them ...

**Comment by bernardomig** [comment]
The messages were updated now. They mimic the ROS system now.

In short: 

```
message DetectedObject {
    // The header of the Object
    Header header = 1;
    // The unique id of the detected object
    uint64 id = 2;
    // The classification label
    string label = 3;
    // The tridimensional bounding box related to the object
    BoundingBox bbox = 4;
}

message Header {
    string frame_id = 1;
    google.protobuf.Timestamp stamp = 2;
}

message BoundingBox {
    Transformation transform = 1;
    Size size = 2;
}

message Transformation {
    Vector origin = 1;
    Quaternion orientation = 2;
}

message Vector {
    float x = 1;
    float y = 2;
    float z = 3;
}

message Quaternion {
    float x = 1;
    float y = 2;
    float z = 3;
    float w = 4;
}

message Size {
    float width  = 1;
    float heigth = 2;
    float depth  = 3;
}
```

**Comment by bernardomig** [comment]
Just update both the client and the server to meet the requirements.

**Comment by miguelriemoliveira** [comment]
Ok, so I will close this issue. @jbga , if you need something else just re-open.
